# Generated by Django 2.2.4 on 2019-08-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('vehicle_model_id', models.IntegerField()),
                ('package_id', models.IntegerField()),
                ('travel_type_id', models.IntegerField()),
                ('from_area_id', models.IntegerField()),
                ('to_area_id', models.IntegerField()),
                ('from_city_id', models.IntegerField()),
                ('to_city_id', models.IntegerField()),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('online_booking', models.IntegerField()),
                ('mobile_site_booking', models.IntegerField()),
                ('booking_created', models.DateTimeField()),
                ('from_lat', models.FloatField()),
                ('from_long', models.FloatField()),
                ('to_lat', models.FloatField()),
                ('to_long', models.FloatField()),
                ('Car_Cancellation', models.IntegerField()),
            ],
        ),
    ]
