# Generated by Django 2.2.4 on 2019-08-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='Car_Cancellation',
            new_name='car_cancellation',
        ),
    ]
