# Generated by Django 2.2.1 on 2019-08-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20190821_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='from_area_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='from_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='from_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
